### ISSUE TITLE
No element named "AvailableSubs" on the xml

### ISSUE THREAD

**Issue by dmeff** [Jlobblet/Barotrauma-Save-Decompressor#2]
I can't for the life of me find the list of available subs on the gamesession.xml file. Am I missing something or is this a bug?

**Comment by Jlobblet** [comment]
Are you decompressing a singleplayer save? In singelplayer the game uses all enabled subs as available and doesn't save a list like is does in multiplayer. If you want to use a new submarine in singleplayer it should be enough to just enable it and then you can buy it.
